let navItemClassName = "hover:text-gray-700 hover:border-gray-300 text-sm border-b2"
let navClassName = "mr-96 sm:mr-0 border-transparent border-b text-sm lg:text-sm w-auto"
let activeClassName = `border-black cursor-default ${navClassName}`
let inactiveClassName = `hover:border-gray-700 sm:hover:text-gray-800 ${navClassName}`
let divideClassName = "divide-y divide-gray-200"
let padding = "p-5"
let h1ClassName = `ring-black ring-opacity-5 bg-white text-3xl font-bold text-gray-900 ${padding}`
let h2ClassName = "text-lg leading-6 font-medium text-gray-900 flex-grow"
let liPrimaryClassName = ""
let liSecondaryClassName = "text-gray-500"
let clickableClassName = "block hover:bg-gray-50"
